# Generated by Django 4.0.4 on 2022-05-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfname', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='media')),
            ],
        ),
    ]
